# fly.toml app configuration file generated for mondo-quest on 2024-06-23T21:03:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mondo-quest'
primary_region = 'ams'

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
